### ISSUE TITLE
misplaced brackets in `read_template`

### ISSUE THREAD

**Issue by blazingarun** [Bart6114/infuser#10]
In this function `read_template` the following line (**line 16**, in **helpers.R**)
```
} else if(is.character(file_or_string) && nchar(file_or_string > 0)){
```
should it not be `nchar(file_or_string) > 0` instead of `nchar(file_or_string > 0)` , I have a huge string which was returning `NA` for the logical operation. I am yet to figure out which specific part of the string is causing this behaviour. Will post that as a test case, once I figure it out.

**Comment by Bart6114** [comment]
Indeed, that was an error. Thanks for catching it. Should be fixed in the latest dev version.
Can you check whether or not it solves your specific problem?

**Comment by blazingarun** [comment]
That was super quick! Yes it now works. 👍
