### ISSUE TITLE
Add option to stop when failing to fill template

### ISSUE THREAD

**Issue by mschubert** [Bart6114/infuser#12]
It would be nice if there was an option so `infuse` would fail if there are unfilled values

**Comment by Bart6114** [comment]
You mean that [here](https://github.com/Bart6114/infuser/blob/4a4b95b1cf9802bab32542888b9e9dbaa1ccc5b9/R/core.R#L87) we do a hard stop instead of a warning?

**Comment by mschubert** [comment]
Yes, but if you want to be backwards compatible rather add an argument to `infuse` on whether to `stop()` or `warning()` (which does the `warning()` by default)

**Comment by Bart6114** [comment]
please check ff2e168, I've added a `strict` argument to `infuse`

**Comment by mschubert** [comment]
Looks good, thank you!

Do you know when you will push this to CRAN?

I'm planning to release a package that depends on this in about 1 week, thinking if I include this or leave the `withCallingHandlers` workaround I currently have.

**Comment by Bart6114** [comment]
I'll push to CRAN in the coming days. If not done by wednesday, feel free to send me a reminder ;)

**Comment by bart6114** [comment]
On CRAN now.
