### ISSUE TITLE
Suggestion for parameters

### ISSUE THREAD

**Issue by saptarshiguha** [Bart6114/infuser#4]
Hello
Very nice package. Does the job. One suggestion, in the call to infuse which is 

    infuse<-function (file_or_string, ..., variable_identifier = c("{{", 
    "}}"), default_char = "|", verbose = FALSE) 

Could the function take an argument, say args_as_list which if non null (or not missing) becomes params_supplied ? So, code like
    
     params_supplied  = if(missing(args_as_list)) list(...) else args_as_list

Sometimes i build my substitution in a list and rather not have to use do.call.
Cheers

**Comment by Bart6114** [comment]
good point, checkout latest commit (5e8c13445e94eba1816ee02fbcf72502de42da19) and the addition to the README
